### PR TITLE
fix(projectDeployToken): Change ListProjectDeployToken to GetProjectDeployToken in Observe

### LINKED ISSUE #83: can't create more than 20 Project DeployTokens
### What happened?

We are trying run some kind of performance tests and we have a script which generates for now 25 objects of `DeployToken.projects.gitlab.crossplane.io`

```yaml
apiVersion: v1
items:
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-1-krm98
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-1
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: 3f72c258-400d-47b6-877c-963761638471-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-10-wk2lw
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-10
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: 811f2459-047d-4792-8942-bbcf7660b9d5-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-11-5l7bj
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-11
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: 556bfee4-25ac-4d88-82db-1f66367f5086-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-12-t5zgx
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-12
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: dc9d48cb-d328-4953-9134-4067d67a008f-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-13-vbjzf
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-13
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: 9c253922-bb5c-456a-a014-409ad885081e-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-14-r29tr
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-14
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: 769fcb95-e3f3-475f-b906-0f7b708cf816-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-15-mgkhm
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-15
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: c72844ef-16ec-4861-9034-311b86c09375-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-16-x57mj
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-16
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: f4ae34d0-184b-4215-8cce-af7823e0c809-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-17-hsfzz
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-17
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: 64bfa11d-3f8f-4565-90bd-68012bb444c7-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-18-vmh9s
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-18
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: 1d47436a-9d34-412a-bbb6-f5e135f6167d-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-19-ffjzb
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-19
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: 38a844a0-3948-4e62-a51e-5f05f5ca043c-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-2-7m8tl
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-2
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: b49fb79f-86fa-4a9b-922b-ebfadcdc2fbe-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-20-mrv9p
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-20
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: 7a00b1e9-0133-4821-83bf-90b64cfc37f7-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-21-dm5hh
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-21
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: c15c1c5f-4913-4707-a2d0-0fe569887b80-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-22-c9mz8
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-22
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: 33ef2ec8-b338-41e0-be26-a8786d4f2544-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-23-nzhv5
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-23
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: f9a0d310-ff06-4ff3-939f-6e87311d83ef-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-24-wqqhd
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-24
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: 591bae0f-1a4f-43bd-af70-e8f6f5e8e646-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-25-99t6h
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-25
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: 3e4e5c92-f7fd-4451-94bf-8da6a29e2f24-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-3-5xtd8
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-3
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: 84176844-e7e9-4347-8dc5-d785bce0c113-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-4-b7vkv
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-4
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: 304ae5bf-af80-40f9-8238-1327f9a4af67-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-5-mtzhb
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-5
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: e030143f-271b-43c9-9310-70d7a19eb839-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-6-4mz99
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-6
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: c7cc0c08-2abf-4f31-bdb6-e4a6a27573f4-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-7-2v5qf
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-7
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: c7669c50-5a26-407f-af4b-396686ade98c-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-8-z2mnj
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-8
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: 649e9e2c-c86a-46d7-8e96-1ddf836a8718-gitlab-deploy-token-48050665
        namespace: crossplane-system
  - apiVersion: projects.gitlab.crossplane.io/v1alpha1
    kind: DeployToken
    metadata:
      name: crossplane-performance-tests-performance-test-9-kkkfc
    spec:
      forProvider:
        projectId: 48050665
        scopes:
          - read_repository
        username: eu1lab-crossplane-performance-tests-performance-test-9
      providerConfigRef:
        name: enterprise-messaging
      writeConnectionSecretToRef:
        name: cfe9999d-4890-4eb5-8ff3-1dc7aaf90783-gitlab-deploy-token-48050665
        namespace: crossplane-system
kind: List
metadata:
  resourceVersion: ""
```

After applying above ManagedResources we can see that non all of them get into `READY=True` state

```
kubectl get deploytokens.projects.gitlab.crossplane.io
NAME                                                     READY   SYNCED   AGE
crossplane-performance-tests-performance-test-1-krm98    True    True     5m55s
crossplane-performance-tests-performance-test-10-wk2lw   True    True     5m55s
crossplane-performance-tests-performance-test-11-5l7bj   True    True     5m55s
crossplane-performance-tests-performance-test-12-t5zgx   True    True     5m55s
crossplane-performance-tests-performance-test-13-vbjzf   True    True     5m55s
crossplane-performance-tests-performance-test-14-r29tr   True    True     5m55s
crossplane-performance-tests-performance-test-15-mgkhm   True    True     5m54s
crossplane-performance-tests-performance-test-16-x57mj   True    True     5m54s
crossplane-performance-tests-performance-test-17-hsfzz   True    True     5m54s
crossplane-performance-tests-performance-test-18-vmh9s   True    True     5m54s
crossplane-performance-tests-performance-test-19-ffjzb   True    True     5m54s
crossplane-performance-tests-performance-test-2-7m8tl    True    True     5m54s
crossplane-performance-tests-performance-test-20-mrv9p   True    True     5m54s
crossplane-performance-tests-performance-test-21-dm5hh   True    True     5m54s
crossplane-performance-tests-performance-test-22-c9mz8   True    True     5m53s
crossplane-performance-tests-performance-test-23-nzhv5   True    True     5m53s
crossplane-performance-tests-performance-test-24-wqqhd   True    True     5m53s
crossplane-performance-tests-performance-test-25-99t6h   True    True     5m53s
crossplane-performance-tests-performance-test-3-5xtd8    True    True     5m53s
crossplane-performance-tests-performance-test-4-b7vkv    True    True     5m53s
crossplane-performance-tests-performance-test-5-mtzhb    False   True     5m53s
crossplane-performance-tests-performance-test-6-4mz99    False   True     5m53s
crossplane-performance-tests-performance-test-7-2v5qf    False   True     5m52s
crossplane-performance-tests-performance-test-8-z2mnj    False   True     5m52s
crossplane-performance-tests-performance-test-9-kkkfc    False   True     5m52s
```

When we run describe on not ready MR we se 2 events:
```
kubectl describe deploytokens.projects.gitlab.crossplane.io crossplane-performance-tests-performance-test-5-mtzhb

Name:         crossplane-performance-tests-performance-test-5-mtzhb
Namespace:
Labels:       <none>
Annotations:  crossplane.io/external-create-pending: 2023-07-27T07:47:39Z
              crossplane.io/external-create-succeeded: 2023-07-27T07:47:40Z
              crossplane.io/external-name: 2295209
API Version:  projects.gitlab.crossplane.io/v1alpha1
...
Events:
  Type    Reason                   Age                   From                 Message
  ----    ------                   ----                  ----                 -------
  Normal  CreatedExternalResource  2m35s (x5 over 10m)   managed/deploytoken  Successfully requested creation of external resource
  Normal  PendingExternalResource  2m35s (x15 over 10m)  managed/deploytoken  Waiting for external resource existence to be confirmed
```

In addition if we look on GitLab Project DeployToken's we can see that not synchronized MR creates over and over again new DeployTokens:

image

image

### What environment did it happen in?
Crossplane version:  `1.12.1`
Crossplane Provider GitLab version: `xpkg.upbound.io/crossplane-contrib/provider-gitlab:v0.3.0`
(also tried latest one from main branch: `xpkg.upbound.io/crossplane-contrib/provider-gitlab:v0.3.0-15.g24fe480`
* Cloud provider: AWS
* Kubernetes version:  EKS 1.24.x

### PR DESCRIPTION
**Pull request by lvvorovi**
Fixes #83 

### How has this code been tested
manually + unit test

### CODE REVIEW

File: pkg/controller/projects/deploytokens/controller.go [hunk 1]
```diff
@@ -95,18 +97,20 @@ func (e *external) Observe(ctx context.Context, mg resource.Managed) (managed.Ex
 		return managed.ExternalObservation{ResourceExists: false}, nil
 	}
 
-	projectDeployTokenID, err := strconv.Atoi(externalName)
+	ID, err := strconv.Atoi(externalName)
```
Comment (MisterMX) [inline pkg/controller/projects/deploytokens/controller.go:100]: Local variables should always be lower case.

```suggestion
	id, err := strconv.Atoi(externalName)
```

**Review by MisterMX — CHANGES_REQUESTED** [review]

**Review by MisterMX — APPROVED** [review]
LGTM. Thank you very much for your contribution @lvvorovi!
